#|SPANISH
Glossary for terminology used in the notes.  The first entry of each entry can be either
a single string or a list of keys that map to the same definition.

If a list of keys is provided, the generated glossary will use the first in the list
when it prints out the glossary for a particular unit
|#
(("funciones de acceso" "funciones para extraer valores de una estructura de datos")
    ("aplicando" "use una función dada en algunas entradas")
    ("argumentos" "las entradas de una función, las expresiones de los argumentos siguen el nombre de una función")
    ("booleano" "un tipo de datos con dos valores: true y false")
    ("llamada" "Utilizando una función dándole entradas")
    ("círculo de evaluación" "un diagrama de la estructura de una expresión (aritmética o código)")
    ("cláusula" "una pregunta y su respuesta correspondiente en una expresión condicional")
    ("condicional" "una expresión de código hecha de preguntas y respuestas")
    ("función constructor" "La función que crea una estructura de datos particular")
    ("contrato" "una declaración del nombre, dominio y rango de una función")
    ("estructura de datos" "Un grupo de valores que se pueden devolver como un único tipo de datos")
    ("tipo de datos" "Una manera de clasificar valores, como: Número, Cadena, Imagen o Booleano")
    ("tipos de datos" "Una forma de clasificar valores, como: Número, Cadena, Imagen o Booleano")
    ("define" "asociar un nombre descriptivo con un valor")
    ("área de definiciones" "el cuadro de texto en el Editor (DrRacket o WeScheme), donde se escriben definiciones de valores y funciones")
    ("receta de diseño" "una secuencia de pasos que ayuda a las personas a documentar, probar y escribir funciones")
    ("dominio" "el tipo de datos que espera una función")
    ("dot-accessors" "Una manera de extraer valores de una estructura de datos")
    ("editor" "software en el que se puede escribir y evaluar código")
    ("mensaje de error" "información del equipo sobre errores en el código")
    ("mensajes de error" "información del equipo sobre errores en el código")
    ("evaluar" "realizar el cálculo en una expresión, producir una respuesta")
    ("equivale a" "el resultado de calcular una expresión")
    ("programacion basada en eventos" "un estilo de programación en el que se escriben todas las funciones para responder a los clics del ratón, pulsaciones de teclas, etc.")
    ("eventos" "algo que sucede fuera de un programa en ejecución, al que el programa puede responder")
    ("ejemplos" "muestra el uso de una función en entradas específicas y el cálculo que debe realizar la función en esas entradas")
    ("expresiones" "un cálculo escrito en las reglas de algún lenguaje (como aritmética, código o un Círculo de Evaluación)")
     ("expresión" "un cálculo escrito en las reglas de algún lenguaje (como aritmética, código o un Círculo de Evaluación)")
    ("definición de función" "que designa una función, enumera sus variables e indica la expresión a calcular cuando se utiliza la función")
    ("función" "un objeto matemático que toma en algunas entradas y produce una salida")
    ("funciones" "un objeto matemático que toma en algunas entradas y produce una salida")
    ("hipotenusa" "el lado opuesto al ángulo de 90 grados en un triángulo rectángulo")
    ("imagen" "un tipo de datos para imágenes")
    ("área de interacciones" "el cuadro de texto en el Editor (DrRacket o WeScheme), donde entramos expresiones para evaluar")
    ("instancias" "Valores específicos de datos")
    ("expresión legal" "expresión que sigue las Reglas de Código para un lenguaje de programación")
    ("expresión matemática" "un cálculo en aritmética")
    ("funciones por trozos" "una función que calcula diferentes expresiones basadas en su entrada")
    ("nombre" "cómo nos referimos a una función o valor definido en un idioma (ejemplos: +, *, estrella, círculo)")
    ("producen" "para calcular un valor de una expresión")
    ("lenguaje de programación" "un conjunto de reglas para escribir código que una computadora puede evaluar")
    ("declaración de propósito" "una breve descripción de lo que hace una función")
    ("rango" "el tipo de datos que produce una función")
    ("cadena de texto" "cualquier secuencia de caracteres entre comillas (ejemplos: \"hello\", \" 42\", \"esto es una cadena! \")")
    ("sintaxis" "El conjunto de reglas que define un lenguaje, ya sea que se hable, se escriba o se programe.")
    ("tipo" "se refiere a un tipo general de datos, como Number, String, Image o Boolean")
    ("tipos" "se refiere a un tipo general de datos, como Number, String, Image o Boolean")
    ("unidad de prueba" "un ejemplo que muestra el uso de una función con un valor o valores específicos y la respuesta que debe producir")
    ("valores" "una pieza específica de datos, como 5 o \" hello \"")
    ("valor" "una pieza específica de datos, como 5 o \" hello \"")
    ("variable" "algo que cambia")
    ("nombre de variable" "nombre de la información que puede ser diferente cada vez que se utiliza una función")
    ("accessor functions" "functions to extract values from a data structure")
))
